#  * [!] The use of implicit sources has been deprecated. To continue using all of the sources currently on your machine, add the following to the top of your Podfile:
source 'https://github.com/CocoaPods/Specs.git'
##  上面的代码 cocoapods 后面 修改的 具体功能还不定 先按要求添加

platform :ios,'7.0'
# 去掉cocoapods 的所有警告
inhibit_all_warnings!
pod 'AFNetworking', '~> 2.5.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'IDMPhotoBrowser', '~> 1.6.2'
#pod 'FMDB/SQLCipher'
#pod 'JSONKit-NoWarning', '~> 1.2'
#pod 'ZXingObjC', '~> 3.0'# 该库用来识别图片中的二维码 暂不用来 扫描二维码 因为效率低的原因
pod 'Masonry', '~> 0.6.1'
#pod 'BaiduMapAPI', '~> 2.7.0'

#pod 'DateTools', '~> 1.6.1'

#友盟
#pod 'UMengMessage'
#pod 'UMengAnalytics'
#pod 'UMengFeedback', '~> 2.0.2'
pod 'PBJVision', '~> 0.4.2'
pod 'SCRecorder'
pod 'BabyBluetooth','~> 0.4.0'
pod 'MJRefresh'

pod 'UzysAssetsPickerController', '~> 0.9.9'
#pod 'MJExtension', '~> 2.1.1'
pod 'EAIntroView', '~> 2.7.4'
pod 'AMScrollingNavbar', '~> 1.3.6'
pod 'DZNEmptyDataSet', ' 1.5.2'
pod 'SCRecorder', '~> 2.4.1'
#pod 'RESideMenu', '~> 4.0.7'
#pod 'REMenu', '~> 1.10'
#pod 'RNFrostedSidebar', '~> 0.2.0'
pod 'BFNavigationBarDrawer', '~> 1.0.2'
#pod 'SlackTextViewController', '~> 1.5'
#pod 'JSQMessagesViewController', '~> 7.0.2'
pod 'MMDrawerController', '~> 0.6.0'
pod 'JDStatusBarNotification', '~> 1.5.2'
pod 'FLAnimatedImage', '~> 1.0.8'
#pod 'SECoreTextView', '~> 0.8.5'
pod 'JTSImageViewController', '~> 1.4'
pod 'VCTransitionsLibrary', '~> 1.5.0'

pod 'FXBlurView', '~> 1.6.2'
#pod 'FXForms', '~> 1.1.6'
pod 'HMSegmentedControl'
#pod 'RSKImageCropper', '~> 1.2.0'
pod 'SVProgressHUD', '~> 1.0'
#pod 'TSMessages', '~> 0.9.12'
pod 'TTTAttributedLabel', '~> 1.10'
#pod 'MarqueeLabel', '~> 2.2.1'    #跑马灯
#pod 'WebViewJavascriptBridge', '~> 4.1.0'
#post_install do |installer_representation|
#    installer_representation.project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
#        end
#end
#end